// SET CONTENT
export const SET_PAGE_TITLE = 'SET_PAGE_TITLE';
export const SET_PAGE_CONTENT = 'SET_PAGE_CONTENT';
export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL";
export const SET_NAVBAR_ACTIVEITEM = 'SET_NAVBAR_ACTIVEITEM';

// SET SHOPPING CART
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

// FEED FIREBASE PRODUCTS
export const BEGIN_PRODUCTS_FEED = "BEGIN_PRODUCTS_FEED";
export const SUCCESS_PRODUCTS_FEED = "SUCCESS_PRODUCTS_FEED";
export const FAIL_PRODUCTS_FEED = "FAIL_PRFAIL_PRODUCTS_FEEDODUCTS_REQUEST";

// REQUEST FIREBASE PRODUCTS
export const BEGIN_PRODUCTS_REQUEST = "BEGIN_PRODUCTS_REQUEST";
export const SUCCESS_PRODUCTS_REQUEST = "SUCCESS_PRODUCTS_REQUEST";
export const FAIL_PRODUCTS_REQUEST = "FAIL_PRODUCTS_REQUEST";
