products = [
    {
        "category": "Textile",
        "name": "Domino wool throw",
        "sku": "sku_313354",
        "price": 82,
        "image": "/images/textile2.png",
        "description": "Keep warm with the cozy Domino wool throw from Klippan Yllefabrik. Klippan Yllefabric was founded in 1879 with a philosophy to combine Swedish ",
        "description_long": "Keep warm with the cozy Domino wool throw from Klippan Yllefabrik. Klippan Yllefabric was founded in 1879 with a philosophy to combine Swedish design with the traditional knowledge of textiles. This particular throw has a simple, classic pattern design and is available in different colors.",
        "currency": "USD",
        "owner_id": 3,
        "countInStock": 10
    },
    {
        "category": "Textile",
        "name": "Pom Pom cushion 45x45 cm",
        "sku": "sku_313355",
        "price": 76,
        "image": "/images/textile1.png",
        "description": "The Pom Pom cushion 45x45 cm from the Swedish By On is a pure dream for those who love soft and cosy styles of decor. This wonderful cushion.",
        "description_long": "The Pom Pom cushion 45x45 cm from the Swedish By On is a pure dream for those who love soft and cosy styles of decor. This wonderful cushion is covered in small, fluffy Pom Poms, which quickly helps you create an inviting and snug feel on your corner sofa, your favourite recliner, or on the bed in the bedroom.",
        "currency": "USD",
        "owner_id": 2,
        "countInStock": 3
    },
    {
        "category": "Tableware",
        "name": "Rustic mug",
        "sku": "sku_313356",
        "price": 6,
        "image": "/images/table1.png",
        "description": "The beautiful Rustic mug from House Doctor is made of ceramics and has an appealing glaze in grey and blue that contributes to a rustic.",
        "description_long": "The beautiful Rustic mug from House Doctor is made of ceramics and has an appealing glaze in grey and blue that contributes to a rustic feeling. Since it's handmade, every mug is unique. Match it with other tableware in the Rustic series.",
        "currency": "USD",
        "owner_id": 2,
        "countInStock": 6
    },
    {
        "category": "Tableware",
        "name": "Essence white wine glass 4-pack",
        "sku": "sku_313358",
        "price": 63,
        "image": "/images/table2.png",
        "description": "These Essence white wine glasses were designed by Alfredo Häberli in 2001. The style and the elegance of these glasses will make your dining",
        "description_long": "These Essence white wine glasses were designed by Alfredo Häberli in 2001. The style and the elegance of these glasses will make your dining",
        "currency": "USD",
        "owner_id": 2,
        "countInStock": 3
    },
    {
        "category": "Home-Accessories",
        "name": "Triplets easter rabbit 3-pack",
        "sku": "sku_622147",
        "price": 16,
        "image": "/images/home1.png",
        "description": "Cas plays modern with rustic wood, framing the rich color and defined grain of natural oak veneer in dark grey high-gloss lacquer.",
        "description_long": "Cas plays modern with rustic wood, framing the rich color and defined grain of natural oak veneer in dark grey high-gloss lacquer. Tinted warm brown with hints of grey, planks of veneer arrange the nightstand's four drawers in seamless asymmetry.",
        "currency": "USD",
        "owner_id": 1,
        "countInStock": 4
    },
    {
        "category": "Home-Accessories",
        "name": "Nova pedal bin",
        "sku": "sku_622146",
        "price": 83,
        "image": "/images/home2.png",
        "description": "The Nova bin by the Danish brand Zone Denmark is the perfect little bin for the bathroom. The bin opens with a foot pedal and is easy to",
        "description_long": "The Nova bin by the Danish brand Zone Denmark is the perfect little bin for the bathroom. The bin opens with a foot pedal and is easy to empty when needed. Available in several wonderful colours and beautiful in combination with other pieces from the Nova collection.",
        "currency": "USD",
        "owner_id": 1,
        "countInStock": 5
    },
    {
        "category": "Lighting",
        "name": "Silvia lamp white",
        "sku": "sku_125983",
        "price": 47,
        "image": "/images/lighting2.png",
        "description": "Renew your home with the trendy Silvia lamp in white designed by the Danish brand Umage / Vita. Silvia is a lampshade made of polypropylene.",
        "description_long": "Renew your home with the trendy Silvia lamp in white designed by the Danish brand Umage / Vita. Silvia is a lampshade made of polypropylene and plastic that comes unassembled with easy mounting instructions. The lampshade can be used both as pendant or table lamp depending how you mount it. Place the lamp in the living room or bedroom and let it spread a nice light! Choose between different sizes.",
        "currency": "USD",
        "owner_id": 1,
        "countInStock": 5
    },
    {
        "category": "Lighting",
        "name": "Luciakör candle arch",
        "sku": "sku_125982",
        "price": 83,
        "image": "/images/lighting1.png",
        "description": "The charming Luciakör electric advent candle holder is a Christmas classic from Star Trading. This candle holder is made of painted wood ...",
        "description_long": "The charming Luciakör electric advent candle holder is a Christmas classic from Star Trading. This candle holder is made of painted wood with carved figures representing Christmas characters that together sing in the choir. All figures have a small light that illuminates the room gently.",
        "currency": "USD",
        "owner_id": 1,
        "countInStock": 8
    },
    {
        "category": "Furniture",
        "name": "High Dot stool leather",
        "sku": "sku_559961",
        "price": 463,
        "image": "/images/furniture1.png",
        "description": "The High Dot stool leather from Fritz Hansen is a stable little seat made from premium leather and three legs of quality steel.",
        "description_long": "The High Dot stool leather from Fritz Hansen is a stable little seat made from premium leather and three legs of quality steel. The original Dot stool design was realized in 1954 by Arne Jacobsen and Fritz Hansen. This is an updated version of the classic, now with a sustainable twist: it utilizes the same high-quality leather as the design icons Ägget and Svanen for its luxurious and comfortable seat. Three braces on the bottom serve as convenient footrests while also providing additional stability. The High Dot stool is perfect for a high desk or kitchen island and makes for a striking interior detail in any design-conscious home.",
        "currency": "USD",
        "owner_id": 1,
        "countInStock": 2
    },
    {
        "category": "Furniture",
        "name": "Frame 49 sidotable with tre lådor",
        "sku": "sku_559960",
        "price": 1151,
        "image": "/images/furniture2.png",
        "description": "The Frame 49 side table with three drawers from By Lassen is a stylish piece of interior decor that beautifully combines functionality and ",
        "description_long": "The Frame 49 side table with three drawers from By Lassen is a stylish piece of interior decor that beautifully combines functionality and aesthetics. The side table has been fashioned from a stately wooden box of drawers housed within a lacquered steel frame. The Frame 35 fits perfectly by the sofa or as a bedside table: it can also be paired with other furnishings to create a larger ensemble in the living room or hallway. Available in a variety of colours.",
        "currency": "USD",
        "owner_id": 1,
        "countInStock": 4
    },
    {
        "category": "Cookware",
        "name": "Satake Kuro chopper",
        "sku": "sku_119140",
        "price": 150,
        "image": "/images/cook1.png",
        "description": "The Satake Kuro Chopper is a handmade and rough forged knife of exceptional quality. It has been developed with a focus on sharpness, precision ",
        "description_long": "The Satake Kuro Chopper is a handmade and rough forged knife of exceptional quality. It has been developed with a focus on sharpness, precision and strength, as evidenced by the 5CR15MOV steel of the blade, which has been processed eight times over. The knife even has a hole to hang it up when not in use. The beautiful burnt wood handle provides excellent stability to an already elegant knife. All of the knives in Satake's Kuro series make perfect gifts for cooking enthusiasts who are looking for high quality knives with a little something special.",
        "currency": "USD",
        "owner_id": 1,
        "countInStock": 7
    },
    {
        "category": "Cookware",
        "name": "Eva Solo knife holder",
        "sku": "sku_119139",
        "price": 102,
        "image": "/images/cook2.png",
        "description": "The stylish and functional knife holder from Eva Solo is available in aluminum or black anodized aluminum and has an easy-to-clean pleated",
        "description_long": "The stylish and functional knife holder from Eva Solo is available in aluminum or black anodized aluminum and has an easy-to-clean pleated removable plastic insert. For all sorts of knives and kitchen tools",
        "currency": "USD",
        "owner_id": 1,
        "countInStock": 5
    }
]
