export const PAGE_CONTENT_SET = 'PAGE_CONTENT_SET';
export const NAVBAR_ACTIVEITEM_SET = 'NAVBAR_ACTIVEITEM_SET';
export const CART_ITEM_ADD = "CART_ITEM_ADD";
export const CART_ITEM_REMOVE = "CART_ITEM_REMOVE";
