// SET CONTENT
export const SET_PAGE_TITLE = 'SET_PAGE_TITLE';
export const SET_PAGE_CONTENT = 'SET_PAGE_CONTENT';
export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL";
export const SET_NAVBAR_ACTIVEITEM = 'SET_NAVBAR_ACTIVEITEM';

// SET SHOPPING CART
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";
export const EMPTY_CART = "EMPTY_CART"

// FEED FIREBASE PRODUCTS
export const BEGIN_PRODUCTS_FEED = "BEGIN_PRODUCTS_FEED";
export const SUCCESS_PRODUCTS_FEED = "SUCCESS_PRODUCTS_FEED";
export const FAIL_PRODUCTS_FEED = "FAIL_PRFAIL_PRODUCTS_FEEDODUCTS_REQUEST";

// REQUEST FIREBASE PRODUCTS
export const BEGIN_PRODUCTS_REQUEST = "BEGIN_PRODUCTS_REQUEST";
export const SUCCESS_PRODUCTS_REQUEST = "SUCCESS_PRODUCTS_REQUEST";
export const FAIL_PRODUCTS_REQUEST = "FAIL_PRODUCTS_REQUEST";

// REQUEST FIREBASE LOGIN
export const BEGIN_LOGIN_REQUEST = "BEGIN_LOGIN_REQUEST";
export const SUCCESS_LOGIN_REQUEST = "SUCCESS_LOGIN_REQUEST";
export const FAIL_LOGIN_REQUEST = "FAIL_LOGIN_REQUEST";
export const REMEMBER_LOGIN = "REMEMBER_LOGIN";

// REQUEST FIREBASE REGISTER
export const BEGIN_REGISTER_REQUEST = "BEGIN_REGISTER_REQUEST";
export const SUCCESS_REGISTER_REQUEST = "SUCCESS_REGISTER_REQUEST";
export const FAIL_REGISTER_REQUEST = "FAIL_REGISTER_REQUEST";

// UPDATE USER INFO
export const BEGIN_UPDATE_USERINFO = "BEGIN_UPDATE_USERINFO";
export const SUCCESS_UPDATE_USERINFO = "SUCCESS_UPDATE_USERINFO";
export const FAIL_UPDATE_USERINFO = "FAIL_UPDATE_USERINFO";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

// CREATE ORDER
export const BEGIN_ORDER_CREATE = 'BEGIN_ORDER_CREATE';
export const SUCCESS_ORDER_CREATE = 'SUCCESS_ORDER_CREATE';
export const FAIL_ORDER_CREATE = 'FAIL_ORDER_CREATE';
export const RESET_ORDER = 'RESET_ORDER';

// PAY ORDER
export const BEGIN_ORDER_PAY = 'BEGIN_ORDER_PAY';
export const SUCCESS_ORDER_PAY = 'SUCCESS_ORDER_PAY';
export const FAIL_ORDER_PAY = 'FAIL_ORDER_PAY';
export const RESET_ORDER_PAY = 'RESET_ORDER_PAY';

// GET ORDER DETAIL
export const BEGIN_ORDER_DETAIL = 'BEGIN_ORDER_DETAIL';
export const SUCCESS_ORDER_DETAIL = 'SUCCESS_ORDER_DETAIL';
export const FAIL_ORDER_DETAIL = 'FAIL_ORDER_DETAIL';
