"""add user_detail table

Revision ID: 6d9b7f13042c
Revises: 1f78069b7b35
Create Date: 2021-12-05 17:04:41.612069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9b7f13042c'
down_revision = '1f78069b7b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
