export const SET_PAGE_CONTENT = 'SET_PAGE_CONTENT';
export const SET_NAVBAR_ACTIVEITEM = 'SET_NAVBAR_ACTIVEITEM';
export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL"
